### ISSUE TITLE
Duplicate Symbol for AFNetworking.

### ISSUE THREAD

**Issue by souravbajlur** [bringg/customer-sdk-ios-demo#1]
I have to add AFNetworking in my project. But when i add this, there shows linkers error for duplicate symbol. I am using AFNetworking version 2.6.3 using cocoa pod. I have also add AFNetworking manually but find same problem. I have followed the instructions given on Bringg developer site (http://developers.bringg.com/docs/bringg-for-ios). @matanporeh, can you help me on this? Thanks in advance.

**Comment by orxelm** [comment]
Hey @souravbajlur,
Can you confirm if this problem still exists?

**Comment by souravbs23** [comment]
No @orxelm , this problem not exists now. I had to solve the problem in other way then.

**Comment by orxelm** [comment]
Glad to hear, let me know if you need anything elese.
I'm closing this issue for now.
